### ISSUE TITLE
Problema al recibir el callback de pago

### ISSUE THREAD

**Issue by milodude** [lexacode/angular-mercadopago#1]
Te comento como lo implemente hasta ahora y si tenes algun comentario o consejo que me guie a llegar a una solucion te lo agradeceria enormemente.

La aplicacion esta hecha en angularJS y  uso c# como servidor(igualmente me gustaria poder manejarlo directamente con el sdk, sin la necesidad de hacer ninguna llamada al servidor, por cuestiones de seguirdad). Hasta ahora logre mostrar el modal de pago provisto por mercado pago utilizando
https://github.com/lexacode/angular-mercadopago

Esta seria mi funcion

$scope.openCheckout = function () {
         mercadopago.openCheckout({
url: 'https://www.mercadopago.com/mla/checkout/start?pref_id=' + $scope.preferenceId
}).then(function (data) {
             // handles the success operation.
             console.log(data);
}, function (err) {
             // handles the failed operation.
             console.log(err);
});
};

Donde $scope.preferenceId es el ID de mi boton de pago en mi perfil creado previamente como indican en la doc del sitio de mercado pago, seccion checkout  basico.

Hasta aca todo bien, el tema pasa que una vez que  quiero probar el recorrido con una tarjeta visa de prueba, automaticamente mercadopago me envia a  un formulario de validacion por parte de la entidad bancaria para aprobar el pago.
Encontre en la documentacion de mercadopago un listado con las tarjetas de prueba, pero esta incompleto debido a que faltan datos para que me acepten la tarjeta. Probe y logre  que que  me envien un mail a mi casilla para aprobar dicho pago llamando al banco, pero la idea seria  para  testear que pase automaticamente y ver el Json de respuesta.

Esta es la info que provee MP para las tarjetas de prueba
https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/test-cards/

Siguiendo la documentacion completo los campos asi
![image](https://user-images.githubusercontent.com/4110660/34641263-1c6feb08-f2e0-11e7-9dac-515aabcd3a46.png)

Los datos del DNI, mes de expiracion y clave de seguridad los complete aleatoriamente por que no dice como hacerlo en la documentacion.
Por ende obtengo esta respuesta

![image](https://user-images.githubusercontent.com/4110660/34641273-3c54bde0-f2e0-11e7-944a-668d2555a135.png)

Consegui entrando a Visa una tarjeta supuestamente de prueba y obtengo este otro resultado. El link de los datos esta acá
https://developer.visa.com/reference

![image](https://user-images.githubusercontent.com/4110660/34641282-550a325c-f2e0-11e7-9673-1d1c66fd7dc1.png)

y este es el mail que me llega

![image](https://user-images.githubusercontent.com/4110660/34641286-6529a3a2-f2e0-11e7-9548-e5ea814ac63c.png)

Evidentemente esta funcionando ok el workflow  pero hay algun tipo de configuracion que  no estoy teniendo en cuenta a la hora de pagar o estoy directamente pegandole  mal a la URL con algun parametro de configuracion erroneo.

Mi aplicacion es http y estoy probandolo desde el localhost, no estoy probando desde la pagina web publicada pq todavia no salimos a produccion.

**Comment by milodude** [comment]
Esto es lo que obtengo cuando abre el modal. Si sirve de algo.

![image](https://user-images.githubusercontent.com/4110660/34641358-b1c74df8-f2e1-11e7-8e07-e7a68053a97c.png)

**Comment by navarroaxel** [comment]
Ayer no lo pude probar porque el **Crear herramienta de cobro** daba error 500 en la web de MP.

Acabo de crear una cuenta de prueba y funciono correctamente el test con la Visa de test que da MP.
![image](https://user-images.githubusercontent.com/1536740/34721154-6a3919e4-f520-11e7-92b1-78531be7a3c9.png)

El error del **cross-origin** a mí tambien me lo da, pero se da dentro de la propia lib de MP **render.js**. Así que no es un error que yo pueda arreglar. De todas formas el modal de **Como quieras pagar?** se abre igual y el usuario puede operar.

Volvé a probar porque quizá estaban actualizando el sistema y por eso el testing no te funcionaba bien. Avisame.

**Comment by milodude** [comment]
Acabo de intentar nuevamente. Los datos de la tarjeta de prueba los saque de esta url [https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/test-cards/](url)

Coloque n  tarjeta:4509 9535 6623 3704, Nombre y apellido: APRO, codigo de seguridad 123 y fecha vencimiento: Una fecha posterior a la actual. (Me pide un mail al cual enviarme los datos de la transaccion posteriormente y le pongo un mail distinto al del que cree el boton.)

Obtengo este resultado

![image](https://user-images.githubusercontent.com/4110660/34721734-acd89138-f522-11e7-879a-93ca465ccf1b.png)

No se porque no veo el mismo mensaje que vos.  :(
 Gracias por responder!! 👍

**Comment by navarroaxel** [comment]
Proba con un nombre y apellido de al menos 2 palabras. Quizá la validación te salta por eso.

**Comment by milodude** [comment]
No. Sigo viendo el mismo error y tmb probe con codigo de seguridad 111. El callback me sigue dando rejected como estado.

**Comment by navarroaxel** [comment]
La demo de este repo te funciona bien si le pones un preferenceId como este: 294828744-374cd19d-3c7d-407b-b805-9109d488b65a? o el tuyo?

Desde que país estás haciendo el testing?

**Comment by milodude** [comment]
El testing lo estoy haciendo desde Argentina. Claro, yo le estaba poniendo el mio que cree en mercado pago con mi usuario de mercado pago que uso generalmente. 
Ahora intentado con ese preference id me aparecio un mensaje de "Una de las partes es un usuario de prueba". En la documentacion estuve leyendo y pense que cuando decia usuario de prueba era regsitrarte con dos mails distintos y probar. Evidentemente algo me estaba faltando. 
Como creo ese usuario de prueba que hiciste vos? via api? y como creo el segundo usuario que evidentemente tambien tiene que ser de prueba? Disculpa por tantas preguntas  pero es la primera vez que me peleo con una API solo.

**Comment by navarroaxel** [comment]
Te paso los 2 usuarios de prueba que cree recien:
"nickname":"TETE8763509","password":"qatest9565"
"nickname":"TT891893","password":"qatest4952"

Los usuarios se crean por medio de una API, o por consola, o usando algo tipo Fiddler.
https://www.mercadopago.com.ar/developers/es/solutions/payments/basic-checkout/test/test-users/

**Comment by milodude** [comment]
Genial!!! ahi mi jefe se dio cuenta con la info que me pasaste de lo que me estaba pasando a mi. Me estaba explicando exactamente lo mismo y como funciona. Ahora necesito seguir terminar con un ticket de mi laburo, ni bien termino eso pruebo una vez mas y posteo la solucion. Pero creo que ya termine de entender como funciona. Gracias por el soporte Axel!!  👍
