### ISSUE TITLE
Modal redirige a chrome

### ISSUE THREAD

**Issue by jonasdiaz** [lexacode/angular-mercadopago#2]
En la web funciona bien el modal de pago, pero en los dispositivos móviles, al empezar con el modal de pago, automáticamente se redirige a el navegador.

**Comment by navarroaxel** [comment]
Lo probé en Android con Chrome y funciona perfectamente.

Usas `browsing in app`? version de browser, de android?

**Comment by jonasdiaz** [comment]
Está mal formulado el issue, la cuestión es que use el plugin en ionic y en el navegador funciona perfecto, además hice la prueba con la extensión de chrome llamada riple, pero al compilar el modal empieza a cargar, automáticamente se redirige a chrome, o al navegador que haya por defecto en el dispositivo móvil.
Será permisos?.
